### ISSUE TITLE
Crash in generate_skillet

### ISSUE THREAD

**Issue by nembery** [PaloAltoNetworks/skilletlib#71]
version 0.1.5.2 causes the following error:

Traceback (most recent call last):
  File "generate_skillet_preview.py", line 33, in <module>
    snippets = p.generate_skillet(from_candidate=from_candidate)
  File "/Users/nembery/.pan_cnc/panhandler/repositories/Skillet Builder Tools/.venv/lib/python3.7/site-packages/skilletlib/panoply.py", line 980, in generate_skillet
    return self.generate_skillet_from_configs(previous_config, latest_config)
  File "/Users/nembery/.pan_cnc/panhandler/repositories/Skillet Builder Tools/.venv/lib/python3.7/site-packages/skilletlib/panoply.py", line 997, in generate_skillet_from_configs
    these_not_found_xpaths = self.__check_element(c, o_xpath, previous_doc, [])
  File "/Users/nembery/.pan_cnc/panhandler/repositories/Skillet Builder Tools/.venv/lib/python3.7/site-packages/skilletlib/panoply.py", line 1148, in __check_element
    new_not_founds = self.__check_element(e, n_xpath, pc, list())
  File "/Users/nembery/.pan_cnc/panhandler/repositories/Skillet Builder Tools/.venv/lib/python3.7/site-packages/skilletlib/panoply.py", line 1148, in __check_element
    new_not_founds = self.__check_element(e, n_xpath, pc, list())
  File "/Users/nembery/.pan_cnc/panhandler/repositories/Skillet Builder Tools/.venv/lib/python3.7/site-packages/skilletlib/panoply.py", line 1148, in __check_element
    new_not_founds = self.__check_element(e, n_xpath, pc, list())
  File "/Users/nembery/.pan_cnc/panhandler/repositories/Skillet Builder Tools/.venv/lib/python3.7/site-packages/skilletlib/panoply.py", line 1077, in __check_element
    found_elements = pc.xpath(xpath)
  File "src/lxml/etree.pyx", line 1581, in lxml.etree._Element.xpath
  File "src/lxml/xpath.pxi", line 305, in lxml.etree.XPathElementEvaluator.__call__
  File "src/lxml/xpath.pxi", line 225, in lxml.etree._XPathEvaluatorBase._handle_result
lxml.etree.XPathEvalError: Invalid predicate

**Comment by nembery** [comment]
multiple xpath attributes can cause a crash. 
attributes in this case was: 

```python

['@id="10360"', '@minver="7.1.0"', '@name="amazon-prime-video"', '@ori_country="USA"', '@ori_language="English"']

```
